# Yelp Restaurant Dataset - Exploratory Data Analysis (EDA)

## Objective

The objective of this notebook is to explore, clean, and analyze the Yelp restaurant dataset to better understand restaurant characteristics, customer ratings, business categories, and geographic distribution.

The insights obtained from this analysis will later be integrated with the customer dataset to support business intelligence, recommendation strategies, and data-driven decision making.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

plt.style.use("default")

In [3]:
yelp_df = pd.read_csv("../data/yelp_restaurants.csv")

In [16]:
yelp_df.head(20)

,alias,title,id,name,price,rating,review_count,distance,coordinates_latitude,coordinates_longitude,location_address1,city
0,asianfusion,Asian Fusion,K3ukx2e11xTRtYBU01dmrA,Salty Flame,No especificado,4.4,184,9568.050891,25.760220,-80.192670,1414 Brickell Ave,Miami
1,steak,Steakhouses,K3ukx2e11xTRtYBU01dmrA,Salty Flame,No especificado,4.4,184,9568.050891,25.760220,-80.192670,1414 Brickell Ave,Miami
2,cocktailbars,Cocktail Bars,K3ukx2e11xTRtYBU01dmrA,Salty Flame,No especificado,4.4,184,9568.050891,25.760220,-80.192670,1414 Brickell Ave,Miami
3,cuban,Cuban,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,Medio,4.4,2965,7035.905420,25.765594,-80.219238,1442 SW 8th St,Miami
4,bars,Bars,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,Medio,4.4,2965,7035.905420,25.765594,-80.219238,1442 SW 8th St,Miami
5,venues,Venues & Event Spaces,UXHxLN3DcDGI57uDIfCuJA,Old's Havana Cuban Bar & Cocina,Medio,4.4,2965,7035.905420,25.765594,-80.219238,1442 SW 8th St,Miami
6,mediterranean,Mediterranean,ix8ifP1jQM9ektdVAs19sQ,Crazy About You,Medio,4.2,2764,9973.468955,25.762015,-80.188986,1155 Brickell Bay Dr,Miami
7,italian,Italian,ix8ifP1jQM9ektdVAs19sQ,Crazy About You,Medio,4.2,2764,9973.468955,25.762015,-80.188986,1155 Brickell Bay Dr,Miami
8,spanish,Spanish,ix8ifP1jQM9ektdVAs19sQ,Crazy About You,Medio,4.2,2764,9973.468955,25.762015,-80.188986,1155 Brickell Bay Dr,Miami
9,italian,Italian,oxtMfBGmVNE18pFVuw7lFg,Fratellino,Alto,4.8,1804,2834.064937,25.749170,-80.260110,264 Miracle Mile,Miami
10,seafood,Seafood,WqIBKxRUPXH3NqTViAHLxQ,Bayshore Club Bar & Grill,Alto,4.3,938,6023.917797,25.728774,-80.234162,3391 Pan American Dr,Miami
11,tradamerican,American,WqIBKxRUPXH3NqTViAHLxQ,Bayshore Club Bar & Grill,Alto,4.3,938,6023.917797,25.728774,-80.234162,3391 Pan American Dr,Miami
12,wine_bars,Wine Bars,WqIBKxRUPXH3NqTViAHLxQ,Bayshore Club Bar & Grill,Alto,4.3,938,6023.917797,25.728774,-80.234162,3391 Pan American Dr,Miami
13,sportsbars,Sports Bars,z1UW-zeI50bMEtGKFtrjmA,Grails Miami - Restaurant & Sports Bar,Medio,4.4,686,10852.715722,25.803184,-80.195219,2800 N Miami Ave,Miami
14,newamerican,New American,z1UW-zeI50bMEtGKFtrjmA,Grails Miami - Restaurant & Sports Bar,Medio,4.4,686,10852.715722,25.803184,-80.195219,2800 N Miami Ave,Miami
15,lounges,Lounges,z1UW-zeI50bMEtGKFtrjmA,Grails Miami - Restaurant & Sports Bar,Medio,4.4,686,10852.715722,25.803184,-80.195219,2800 N Miami Ave,Miami
16,italian,Italian,eVhl0Yu1ZRWRD2D1OQGsYg,Capriccio Blue Lagoon,No especificado,4.5,124,3183.705118,25.781460,-80.287858,5600 Blue Lagoon Dr,Miami
17,desserts,Desserts,eVhl0Yu1ZRWRD2D1OQGsYg,Capriccio Blue Lagoon,No especificado,4.5,124,3183.705118,25.781460,-80.287858,5600 Blue Lagoon Dr,Miami
18,newamerican,New American,pUg9rFqeiSIWcWUqri_47w,Sixty Vines,No especificado,4.7,136,10209.090967,25.781526,-80.191181,150 NE 8th St.,Miami
19,breakfast_brunch,Breakfast & Brunch,pUg9rFqeiSIWcWUqri_47w,Sixty Vines,No especificado,4.7,136,10209.090967,25.781526,-80.191181,150 NE 8th St.,Miami

In [17]:
yelp_df.shape

(463, 12)

In [18]:
yelp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   alias                  463 non-null    str
 1   title                  463 non-null    str
 2   id                     463 non-null    str
 3   name                   463 non-null    str
 4   price                  463 non-null    str
 5   rating                 463 non-null    float64
 6   review_count           463 non-null    int64
 7   distance               463 non-null    float64
 8   coordinates_latitude   463 non-null    float64
 9   coordinates_longitude  463 non-null    float64
 10  location_address1      463 non-null    str
 11  city                   463 non-null    str
dtypes: float64(4), int64(1), str(7)
memory usage: 43.5 KB

In [28]:
yelp_df.describe()

,rating,review_count,distance,coordinates_latitude,coordinates_longitude
count,463.000000,463.000000,463.000000,463.000000,463.000000
mean,4.342117,538.408207,6155.117432,25.764661,-80.254168
std,0.332863,852.570412,3175.186957,0.029770,0.048691
min,2.700000,1.000000,132.202770,25.682257,-80.393596
25%,4.100000,87.500000,3175.275975,25.749597,-80.281227
50%,4.400000,248.000000,5518.960654,25.765025,-80.257420
75%,4.500000,686.000000,9375.791147,25.782240,-80.210630
max,5.000000,6869.000000,13539.614717,25.842900,-80.185336

In [29]:
yelp_df.columns

Index(['alias', 'title', 'id', 'name', 'price', 'rating', 'review_count',
       'distance', 'coordinates_latitude', 'coordinates_longitude',
       'location_address1', 'city'],
      dtype='str')

In [30]:
yelp_df.isnull().sum()

alias                    0
title                    0
id                       0
name                     0
price                    0
rating                   0
review_count             0
distance                 0
coordinates_latitude     0
coordinates_longitude    0
location_address1        0
city                     0
dtype: int64

In [35]:
yelp_df["name"].value_counts()

name
La Cañita                                   6
CVI.CHE 105                                 5
Salty Flame                                 3
Old's Havana Cuban Bar & Cocina             3
Crazy About You                             3
                                           ..
Hemingways on the Beach Turks and Caicos    1
Lili’s Mediterranean Food                   1
Namaste Miami                               1
To Be Determined                            1
Central Fare Food Collective                1
Name: count, Length: 198, dtype: int64